kind = "web"
previewPath = "/"
title = "CureBery - Platform Perawat Online"
version = "1.0.0"
id = "artifacts/cure-bery"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20735

[services.env]
PORT = "20735"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/cure-bery run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/cure-bery", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"
BASE_PATH = "/"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/cure-bery", "run", "serve"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"
